"""
Column labels in the images file.
"""
project_id = "project_id"
deployment_id = "deployment_id"
date = "timestamp"
class_ = "class"
order = "order"
family = "family"
genus = "genus"
species = "species"
name = "common_name"
url = "location"
