"""
Column labels in the images file.
"""
deployment_id = "deployment_id"
date = "timestamp"
class_ = "class"
order = "order"
family = "family"
genus = "genus"
epithet = "species"
name = "common_name"
