site_name: wiutils
repo_url: https://github.com/PEM-Humboldt/wiutils
copyright: Copyright &copy; 2021-2022 Programa de Evaluación y Monitoreo de la Biodiversidad - Instituto de Investigación de Recursos Biológicos Alexander von Humboldt

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

nav:
  - Getting started: index.md
  - Reference:
      - Darwin Core: reference/darwincore.md
      - Extraction: reference/extraction.md
      - Filtering: reference/filtering.md
      - Plotting: reference/plotting.md
      - Preprocessing: reference/preprocessing.md
      - Reading: reference/reading.md
      - Summarizing: reference/summarizing.md


  - Contribute: contribute.md

extra:
  generator: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: numpy
          setup_commands:
            - import sys
            - from unittest.mock import MagicMock as mock
            - sys.modules["cv2"] = mock()
            - sys.modules["ffmpeg"] = mock()
            - sys.modules["matplotlib"] = mock()
            - sys.modules["numpy"] = mock()
            - sys.modules["pandas"] = mock()
            - sys.modules["PIL"] = mock()
            - sys.modules["seaborn"] = mock()
          rendering:
            show_root_heading: true

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
