site_name: wiutils
repo_url: https://github.com/PEM-Humboldt/wiutils
copyright: Copyright &copy; 2021-2022 Programa de Evaluación y Monitoreo de la Biodiversidad - Instituto de Investigación de Recursos Biológicos Alexander von Humboldt

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

nav:
  - Getting started: index.md
  - User guide:
      - guide/index.md
      - Reading: guide/reading.md
      - Extraction: guide/extraction.md
      - Filtering: guide/filtering.md
      - Summarizing: guide/summarizing.md
      - Plotting: guide/plotting.md
      - Darwin Core: guide/darwincore.md
      - Preprocessing: guide/preprocessing.md
  - Reference: reference.md

  - Contribute: contribute.md

extra:
  generator: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: numpy
          rendering:
            docstring_section_style: table
            heading_level: 2
            show_root_heading: true
            show_submodules: false

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
